---
- name: Install 'language-pack-{{ locale[0:2] }}'
  ansible.builtin.package:
    name: language-pack-{{ item[0:2] }}
    state: present
  with_items:
    - "{{ locale }}"
  when: ansible_distribution == 'Ubuntu'

- name: Generate locale for '{{ locale }}'
  ansible.builtin.locale_gen:
    name: "{{ locale }}"
    state: present

- name: Check localectl status
  ansible.builtin.command: localectl status
  register: localectl_status
  changed_when: false

- name: Get current system settings
  ansible.builtin.set_fact:
    keymap_current: "{{ localectl_status.stdout | regex_search('Keymap: ([^\n]+)', '\\1') | first }}"
    locale_current: "{{ localectl_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
    language_current: "{{ localectl_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale], true) | first }}"

- name: Set locale to '{{ locale }}', language to '{{ language }}'
  ansible.builtin.command: localectl set-locale LANG={{ locale }} LANGUAGE={{ language }}
  when: locale_current != locale or language_current != language

- name: Set keyboard layout
  ansible.builtin.command: localectl set-keymap --no-convert {{ keymap }}
  when: keymap_current != keymap
