---
- name: Install 'language-pack-{{ lang[0:2] }}'
  ansible.builtin.package:
    name: language-pack-{{ item[0:2] }}
    state: present
  with_items:
    - "{{ lang }}"
  when: ansible_distribution == 'Ubuntu'

- name: Generate locale for '{{ lang }}'
  ansible.builtin.locale_gen:
    name: "{{ lang }}"
    state: present

- name: Check localectl status
  ansible.builtin.command: localectl status
  register: localectl_status
  changed_when: false

- name: Get current system settings
  ansible.builtin.set_fact:
    keymap_current: "{{ localectl_status.stdout | regex_search('Keymap: ([^\n]+)', '\\1') | first }}"
    lang_current: "{{ localectl_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
    language_current: "{{ localectl_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale], true) | first }}"

- name: Set LANG to '{{ lang }}', LANGUAGE to '{{ language }}'
  ansible.builtin.command: localectl set-locale LANG={{ lang }} LANGUAGE={{ language }}
  when: lang_current != lang or language_current != language

- name: Set keyboard layout
  ansible.builtin.command: localectl set-keymap --no-convert {{ keymap }}
  when: keymap_current != keymap
